AppWeb/urls.py
from django.urls import path
from . import views
from AppWeb import views

# Esta variable app_name sirve para que Django pueda diferenciar las URL de cada proyecto
app_name = 'gestion'

urlpatterns = [
    path('AppWeb/listadoEmpleados/', views.ListaEmpleado.as_view(), name='listado-empleado'),
    path('AppWeb/listadoEquipos/', views.ListaEquipo.as_view(), name='listado-equipo'),
    path('AppWeb/listadoTickets/', views.ListaTicket.as_view(), name='listado-ticket'),
    
    path('AppWeb/creaEmpleado/',views.CrearEmpleado.as_view(), name='crear-empleado'),
    path('AppWeb/creaEquipo/',views.CrearEquipo.as_view(), name='crear-equipo'),
    path('AppWeb/creaTicket/',views.CrearTicket.as_view(), name='crear-ticket'),
    
    path('AppWeb/borrarEmpleado/<int:pk>/',views.BorrarEmpleado.as_view(), name='borrar-empleado'),
    path('AppWeb/borrarEquipo/<int:pk>/',views.BorrarEquipo.as_view(), name='borrar-equipo'),
    path('AppWeb/borrarTicket/<int:pk>/',views.BorrarTicket.as_view(), name='borrar-ticket'),
    
    path('AppWeb/modificarEmpleado/<int:pk>/',views.ModificarEmpleado.as_view(), name='modificar-empleado'),
    path('AppWeb/modificarEquipo/<int:pk>/',views.ModificarEquipo.as_view(), name='modificar-equipo'),
    path('AppWeb/modificarTicket/<int:pk>/',views.ModificarTicket.as_view(), name='modificar-ticket'),
    
    path('AppWeb/listadoEmpleados/<int:pk>',views.DetalleEmpleado.as_view(), name='detalle-empleado'),
    path('AppWeb/listadoEquipos/<int:pk>',views.DetalleEquipo.as_view(), name='detalle-equipo'),
    path('AppWeb/listadoTickets/<int:pk>',views.DetalleTicket.as_view(), name='detalle-ticket'),
    
    path('', views.loginPage, name="login"),
    path('', views.logoutUser, name="logout"),

    path('apiempleados', views.EmpListView.as_view(), name= 'listaempleados-api'),
    path('apiempleados/<int:pk>', views.EmpDetailView.as_view(), name= 'listaempleado-api'),

    path('apiequipos', views.EquListView.as_view(), name= 'listaequipo-api'),
    path('apiequipos/<int:pk>', views.EquDetailView.as_view(), name= 'listaequipo-api'),

    path('apitickets', views.TicListView.as_view(), name= 'listaticket-api'),
    path('apitickets/<int:pk>', views.TicDetailView.as_view(), name= 'listaticket-api'),
    
]

Reto_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppWeb.urls')),
]

AppWeb/models.py
from django.db import models

# Creacion de la clase equipo

class Equipo(models.Model):
    nserie = models.CharField(max_length=20, unique=True)
    modelo = models.CharField(max_length=50)
    marca = models.CharField(max_length=30)
    tipo = models.CharField(max_length=20)
    fechaAdquisicion = models.DateField(null=True, blank=True)
    fechaPuestaMarcha = models.DateField(null=True, blank=True)
    provNombre = models.CharField(max_length=30)
    provTelefono = models.IntegerField(default=0)
    planta = models.CharField(max_length=15)

    # Devuelve un string con la marca, el modelo, y el numero de serie de cada Equipo creado.
    def __str__(self):
        return f" Equipo: {self.marca} {self.modelo}. Número de serie: {self.nserie}"


# Creacion de la clase Ticket
class Ticket(models.Model):
    nref = models.CharField(max_length = 20, unique=True)
    titulo = models.CharField(max_length = 10)
    descripcion = models.CharField(max_length = 50)
    fechaApertura = models.DateField(null=True, blank=True)
    fechaResolucion = models.DateField(null=True, blank=True)
    nivelUrgencia = models.ForeignKey('NivelUrgencia', on_delete=models.CASCADE) # relación one-to-many para seleccionar el nivel de urgencia
    tipo = models.ForeignKey('TipoTicket', on_delete=models.CASCADE) # relación one-to-many para seleccionar el tipo de ticket
    estado = models.ForeignKey('EstadoTicket', on_delete=models.CASCADE) # relación one-to-many para seleccionar el estado del ticket
    empleado = models.ForeignKey('Empleado', on_delete=models.CASCADE, default="") # relación one-to-many, un ticket solo es atendido por un empleado
    equipo = models.ForeignKey('Equipo', on_delete=models.CASCADE, default="") # relación one-to-many, un ticket solo puede tener un equipo
    comentarios = models.CharField(max_length = 40)
    
    #Devuelve un string con la referencia, el titulo, y la descripcion de cada Equipo creado.
    def __str__(self):
        return f" Referencia: {self.nref}. Titulo: {self.titulo}. Descripción: {self.descripcion}"

# Creacion de la clase Empleado
class Empleado(models.Model):
    dni = models.CharField(max_length=9, unique=True)
    nombre = models.CharField(max_length=15)
    apellidos = models.CharField(max_length=25)
    email = models.CharField(max_length=30)
    telefono = models.IntegerField(default=0)

    # Devuelve un string con el nombre, apellido y DNI del empleado

    def __str__(self):
        return f" Nombre: {self.nombre}. {self.apellidos}. DNI: {self.dni}"

class NivelUrgencia(models.Model):
    nombre = models.CharField(max_length=20)
    
    def __str__(self):
        return f" Nivel: {self.nombre}"

class TipoTicket(models.Model):
    nombre = models.CharField(max_length=20)
    
    def __str__(self):
        return f" Tipo: {self.nombre}"
    
class EstadoTicket(models.Model):
    nombre = models.CharField(max_length=20)
    
    def __str__(self):
        return f" Estado: {self.nombre}"

AppWeb/forms.py
from django.forms import ModelForm
from django import forms
from .models import Ticket, Empleado, Equipo


# Formulario asociado a la clase Equipo
class FormEquipo(forms.ModelForm):
    class Meta:
        model = Equipo
        fields = '__all__'
        labels = {
        "nserie": "Número de serie",
        "fechaAdquisicion": "Fecha de adquisición",
        "fechaPuestaMarcha": "Fecha de puesta en marcha",
        "provNombre": "Nombre del proveedor",
        "provTelefono": "Teléfono del proveedor"}

        widgets = {
            'nserie': forms.TextInput(attrs={'class':'form-control'}),
            'modelo': forms.TextInput(attrs={'class':'form-control'}),
            'marca': forms.TextInput(attrs={'class':'form-control'}),
            'tipo': forms.TextInput(attrs={'class':'form-control'}),
            'fechaAdquisicion': forms.DateInput(attrs={'class':'form-control'}),
            'fechaPuestaMarcha': forms.DateInput(attrs={'class':'form-control'}),
            'provNombre': forms.TextInput(attrs={'class':'form-control'}),
            'provTelefono': forms.NumberInput(attrs={'class':'form-control'}),
            'planta': forms.TextInput(attrs={'class':'form-control'}),
        }
 

# Formulario asociado a la clase Ticket
class FormTicket(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = '__all__'
        labels = {
        "nref": "Número de referencia",
        "fechaApertura": "Fecha de apertura",
        "fechaResolucion": "Fecha de resolución",
        "nivelUrgencia": "Nombre de urgencia",
        }
        widgets = {
            'nref': forms.TextInput(attrs={'class': 'form-control'}),
            'titulo': forms.TextInput(attrs={'class': 'form-control'}),
            'descripcion': forms.TextInput(attrs={'class': 'form-control'}),
            'fechaApertura': forms.DateInput(attrs={'class': 'form-control'}),
            'fechaResolucion': forms.DateInput(attrs={'class': 'form-control'}),
            'nivelUrgencia': forms.Select(attrs={'class': 'form-control'}),
            'tipo': forms.Select(attrs={'class': 'form-control'}),
            'estado': forms.Select(attrs={'class': 'form-control'}),
            'empleado': forms.Select(attrs={'class': 'form-control'}),
            'equipo': forms.Select(attrs={'class': 'form-control'}),
            'comentarios': forms.TextInput(attrs={'class': 'form-control'}),
            
        }


# Formulario asociado a la clase Empleado
class FormEmpleado(ModelForm):
    class Meta:
        model = Empleado
        fields = '__all__'
        labels = {
        "dni": "DNI",
        "nombre": "Nombre",
        "apellidos": "Apellidos",
        "email": "Email",
        "telefono": "Teléfono",
        }
        widgets = {
            'dni': forms.TextInput(attrs={'class':'form-control'}),
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'apellidos': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.EmailInput(attrs={'class':'form-control'}),
            'telefono': forms.NumberInput(attrs={'class':'form-control'}),
        }



    

AppWeb/views.py
from typing import Any, Dict
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView, View
from .models import Empleado, Equipo, Ticket
from .forms import FormEmpleado, FormTicket, FormEquipo
from django.contrib.auth import authenticate,login
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse_lazy
from django.db.models import Q
from django.http import JsonResponse
from django.forms import model_to_dict

#Vistas para listar
class ListaEmpleado(ListView):
    model = Empleado
    template_name = 'listadoEmpleados.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        queryset = super().get_queryset()
        busqueda = self.request.GET.get("buscar")

        if busqueda:
            queryset = queryset.filter(
                Q(dni__icontains=busqueda) |
                Q(nombre__icontains=busqueda) |
                Q(apellidos__icontains=busqueda)
            ).distinct()

        return queryset
    
class ListaEquipo(ListView):
    model = Equipo
    template_name = 'listadoEquipos.html'
    context_object_name = 'equipos'

    def get_queryset(self):
        queryset = super().get_queryset()
        busqueda = self.request.GET.get("buscar")

        if busqueda:
            queryset = queryset.filter(
                Q(nserie__icontains=busqueda) |
                Q(modelo__icontains=busqueda) |
                Q(marca__icontains=busqueda)
            ).distinct()

        return queryset
    
class ListaTicket(ListView):
    model = Ticket
    template_name = 'listadoTickets.html'
    context_object_name = 'tickets'

    def get_queryset(self):
        queryset = super().get_queryset()
        busqueda = self.request.GET.get("buscar")

        if busqueda:
            queryset = queryset.filter(
                Q(nref__icontains=busqueda) |
                Q(titulo__icontains=busqueda) |
                Q(descripcion__icontains=busqueda)
            ).distinct()

        return queryset

#Vistas para Crear objetos    
class CrearEmpleado(CreateView):
    form_class = FormEmpleado
    template_name = 'creaEmpleado.html'
    model = Empleado
    success_url = reverse_lazy('gestion:listado-empleado')

class CrearEquipo(CreateView):
    form_class = FormEquipo
    template_name = 'creaEquipo.html'
    model = Equipo
    success_url = reverse_lazy('gestion:listado-equipo')

class CrearTicket(CreateView):
    form_class = FormTicket
    template_name = 'creaTicket.html'
    model = Ticket
    success_url = reverse_lazy('gestion:listado-ticket')

#Vistas para borrar
class BorrarEmpleado(DeleteView):
    template_name = 'borrarEmpleado.html'
    model = Empleado
    success_url = reverse_lazy('gestion:listado-empleado')
    
class BorrarEquipo(DeleteView):
    template_name = 'borrarEquipo.html'
    model = Equipo
    success_url  = reverse_lazy('gestion:listado-equipo')
    
class BorrarTicket(DeleteView):
    template_name = 'borrarTicket.html'
    model = Ticket
    success_url = reverse_lazy('gestion:listado-ticket')
    
#Vistas para modificar
class ModificarEmpleado(UpdateView):
    form_class = FormEmpleado
    template_name = 'creaEmpleado.html'
    model = Empleado
    success_url = reverse_lazy('gestion:listado-empleado')

class ModificarEquipo(UpdateView):
    form_class = FormEquipo
    template_name = 'creaEquipo.html'
    model = Equipo
    success_url = reverse_lazy('gestion:listado-equipo')

class ModificarTicket(UpdateView):
    form_class = FormTicket
    template_name = 'creaTicket.html'
    model = Ticket
    success_url = reverse_lazy('gestion:listado-ticket')

#Vistas para los formularios
def post_form(request):
    nombre = request.POST["nombre"]
    apellido = request.POST["apellido"]
    dni = request.POST["dni"]
    email = request.POST["email"]
    telefono = request.POST["telefono"]   
    return HttpResponse(f"Se ha registrado a {nombre} {apellido} con DNI {dni}")  

#Vistas para mostrar en detalle
class DetalleEmpleado(DetailView):
    template_name = 'detalleEmpleado.html'
    model = Empleado


class DetalleEmpleado(DetailView):
    template_name = 'detalleEmpleado.html'
    model = Empleado

class DetalleEmpleado(DetailView):
    template_name = 'detalleEmpleado.html'
    model = Empleado

class DetalleEquipo(DetailView):
    template_name = 'detalleEquipo.html'
    model = Equipo

class DetalleTicket(DetailView):
    template_name = 'detalleTicket.html'
    model = Ticket

#Vista de login
def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
    
        if user is not None:
            login (request,user)
            return redirect('/AppWeb/listadoEmpleados')
        else:
            messages.info(request, 'Usuario o contraseña incorrectos')
    context = {}
    return render(request, 'login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('login.html')


class EmpListView(View):
    def get (self, request) :
        if ('dni' in request.GET):
            eList = Empleado.objects.filter(dni__contains=request.GET('dni'))
        else:
            eList = Empleado.objects.all()
            return JsonResponse(list(eList.values()), safe=False)

class EmpDetailView(View):
    def get (self, request, pk) :
        empleo = Empleado.objects.get(pk=pk)
        return JsonResponse(model_to_dict(empleo))
    

    
class EquListView(View):
    def get (self, request) :
        if ('nserie' in request.GET):
            eqList = Equipo.objects.filter(nserie__contains=request.GET('nserie'))
        else:
            eqList = Equipo.objects.all()
            return JsonResponse(list(eqList.values()), safe=False)

class EquDetailView(View):
    def get (self, request, pk) :
        equipo = Equipo.objects.get(pk=pk)
        return JsonResponse(model_to_dict(equipo))
    

    
class TicListView(View):
    def get (self, request) :
        if ('nref' in request.GET):
            tList = Ticket.objects.filter(nref__contains=request.GET('nref'))
        else:
            tList = Ticket.objects.all()
            return JsonResponse(list(tList.values()), safe=False)

class TicDetailView(View):
    def get (self, request, pk) :
        ticket = Ticket.objects.get(pk=pk)
        return JsonResponse(model_to_dict(ticket))
    

AppWeb/templates/borrarEmpleado.html
{% extends "homeEmpleados.html" %}
{% load static %}

{% block contenido %}
<div class="contenido">
<form method="POST">
    {% csrf_token %}
    <h4>¿Desea dar de baja al empleado seleccionado?</h4>
    <button class='si' type="submit">Si</button>
    <a href="{% url 'gestion:listado-empleado' %}" class=" botonno no" >No</a>
</form>
</div>
{% endblock %}

AppWeb/templates/borrarEquipo.html
{% extends "homeEquipos.html" %}
{% load static %}

{% block contenido %}
<div class="contenido">
<form method="POST">
    {% csrf_token %}
    <h4>¿Desea dar de baja el equipo seleccionado?</h4>
    <button class='si' type="submit">Si</button>
    <a href="{% url 'gestion:listado-equipo' %}" class=" botonno no" >No</a>
</form>
</div>
{% endblock %}

AppWeb/templates/borrarTicket.html
{% extends "homeTickets.html" %}
{% load static %}

{% block contenido %}
<div class="contenido">
<form method="POST">
    {% csrf_token %}
    <h4>¿Desea dar de baja el ticket seleccionado?</h4>
    <button class='si' type="submit">Si</button>
    <a href="{% url 'gestion:listado-ticket' %}" class=" botonno no" >No</a>
</form>
</div>
{% endblock %}

AppWeb/templates/creaEmpleado.html
{% extends "homeEmpleados.html" %}
{% load static %}

{% block contenido %}
<div class="contenido">
    <h2>CREAR O EDITAR EMPLEADO</h2>
    <form method="POST" id="miFormulario" novalidate>
        {% csrf_token %} {{form.as_p}}
        <button type="submit" class="Guardar">Guardar</button>
        <a href="{% url 'gestion:listado-empleado' %}"><img class="atras" src="{% static 'images/back.png' %}"
                width="70px" title="Volver a la página anterior"></a>
    </form>
    <div id="mensajeError"></div>
</div>
{% endblock %}

AppWeb/templates/detalleEmpleado.html
{% extends "homeEmpleados.html" %}
{% load static %}

{% block contenido %}
{% if empleado %}
<div class="contenido">
    <h2>DETALLES DEL EMPLEADO {{empleado.id}}</h2>

    <ul class="detalles">
        <li>
            <p><b>Nombre y Apellidos: </b>{{empleado.nombre}} {{empleado.apellidos}} </p>
        </li>
        <li>
            <p><b>DNI: </b>{{empleado.dni}}</p>
        </li>
        <li>
            <p><b>Teléfono: </b>{{empleado.telefono}}</p>
        </li>
        <li>
            <p><b>Email: </b>{{empleado.email}}</p>
        </li>
    </ul>

    {% else %}
    <p>No existe este empleado.</p>
    {% endif %}

    <a href="{% url 'gestion:modificar-empleado' empleado.id %}"><img src="{% static 'images/editar.png' %}" width="51px"
        title="Haz clic para editar este empleado"></a>
    <a href="{% url 'gestion:listado-empleado' %}"><img class="atras" src="{% static 'images/back.png' %}" width="100px"
            title="Pulsa para volver a la página anterior"></a>

</div>
{% endblock %}

AppWeb/templates/detalleEquipo.html
{% extends "homeEquipos.html" %}
{% load static %}

{% block contenido %}
{% if equipo %}
<div class="contenido"> 
    <h2>DETALLES DEL EQUIPO {{equipo.id}}</h2>

    <ul class="detalles">
        <li>
            <p><b>Número de serie: </b>{{equipo.nserie}} </p>
        </li>
        <li>
            <p><b>Modelo: </b>{{equipo.modelo}}</p>
        </li>
        <li>
            <p><b>Marca: </b>{{equipo.marca}}</p>
        </li>
        <li>
            <p><b>Tipo: </b>{{equipo.tipo}}</p>
        </li>
        <li>
            <p><b>Fecha de Adquisición: </b>{{equipo.fechaAdquisicion}} </p>
        </li>
        <li>
            <p><b>Fecha de puesta en marcha: </b>{{equipo.fechaPuestaMarcha}} </p>
        </li>
        <li>
            <p><b>Nombre y teléfono del proveedor: </b>{{equipo.provNombre}} . {{equipo.provTelefono}}</p>
        </li>
        <li>
            <p><b>Planta: </b>{{equipo.planta}}</p>
        </li>
    </ul>

    {% else %}
    <p>No existe el equipo seleccionado.</p>
    {% endif %}
    <a href="{% url 'gestion:modificar-equipo' equipo.id %}"><img src="{% static 'images/editar.png' %}" width="51px"
        title="Haz clic para editar este equipo"></a>
    <a href="{% url 'gestion:listado-equipo' %}"><img class="atras" src="{% static 'images/back.png' %}" title="Pulsa para volver a la página anterior"></a>
</div>
{% endblock %}

AppWeb/templates/detalleTicket.html
{% extends "homeTickets.html" %}
{% load static %}

{% block contenido %}
{% if ticket %}
<div class="contenido"> 
    <h2>DETALLES DEL TICKET {{ticket.id}}</h2>

    <ul class="detalles">
        <li>
            <p><b>Número de referencia: </b>{{ticket.nref}} </p>
        </li>
        <li>
            <p><b>Título: </b>{{ticket.titulo}}</p>
        </li>
        <li>
            <p><b>Descripción: </b>{{ticket.descripcion}}</p>
        </li>
        <li>
            <p><b>Fecha de apertura: </b>{{ticket.fechaApertura}}</p>
        </li>
        <li>
            <p><b>Fecha de resolucion: </b>{{ticket.fechaResolucion}} </p>
        </li>
        <li>
            <p><b>Nivel de urgencia: </b>{{ticket.nivelUrgencia}} </p>
        </li>
        <li>
            <p><b>Tipo de ticket: </b>{{ticket.tipo}}</p>
        </li>
        <li>
            <p><b>Estado de ticket: </b>{{ticket.estado}}</p>
        </li>
        <li>
            <p><b>Empleado: </b>{{ticket.empleado}}</p>
        </li>
        <li>
            <p><b>Ticket del equipo: </b>{{ticket.equipo}}</p>
        </li>
        <li>
            <p><b>Comentarios: </b>{{ticket.comentarios}}</p>
        </li>
    </ul>

    {% else %}
    <p>No existe el ticket seleccionado.</p>
    {% endif %}
    <a href="{% url 'gestion:modificar-ticket' ticket.id %}"><img src="{% static 'images/editar.png' %}" width="51px"
        title="Haz clic para editar este ticket"></a>
    <a href="{% url 'gestion:listado-ticket' %}"><img class="atras" src="{% static 'images/back.png' %}" title="Pulsa para volver a la página anterior"></a>
</div>
{% endblock %}

AppWeb/templates/login.html
<!DOCTYPE html>
<html lang="es">

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/css/Estilo.css">
    <title> Deustomach Innovation S.L.</title>
</head>

<body>
    <div class="contenidoLog">
        <div id="logoLog">
            <img alt="Icono login" src="../static/images/log.png" width="300px" height="100px" title="icono login">
        </div>
        <div id="formularioLog">
            <form method="POST" action="">
                {% csrf_token %}
                <div id="usuarioLog">
                    <div class="addonLog">
                        <span class="addon-texto"><i class="fas"></i></span>
                    </div>
                    <input type="text" name="username" placeholder="Usuario..." class="campo">
                </div>
                <div id="addon-mb">
                    <div class="addonLog">
                        <span class="addon-texto"><i class="fas"></i></span>
                    </div>
                    <input type="password" name="password" placeholder="Contraseña..." class="campo">
                </div>

                <div class="flexCentro">
                    <input class="botonLog" type="submit" value="Iniciar Sesión">
                </div>
            </form>
        </div>
        {{form.errors}}
        {% for message in messages %}
        <p id="mensaje">{{message}}</p>
        {% endfor %}
        <div id="mt-2">
            <p>¿Necesitas una cuenta?</p>
            <p><i>Contacta con nuestro administrador</i></p>
            <a href="http://127.0.0.1:8000/admin/" id='logadmin'><p>Accede como administrador</p></a>
        </div>
</body>

</html>